export const initialState = {
  plants: {
    data: [
      // {
      //   id: '1',
      //   polishName: 'Hortensja bukietowa',
      //   latinName: 'Hydrangea paniculata',
      //   type: 'Vanille Fraise Renhy',
      //   content: 'Nowa odmiana hortensji bukietowej o dużej wartości dekoracyjnej. Krzew o wyprostowanym pokroju, dorastający do 2 m wys. i 1,5 m szer. Pędy ciemnoczerwone. Kwiaty płonne, zebrane w wiechowate, bardzo duże kwiatostany, do 40 cm dł. Barwa kwiatów początkowo biała, szybko zmienia się na intensywnie różową, a nawet czerwoną. Kwitnie od VII do X. Wymaga gleb lekko kwaśnych, próchnicznych, ale dobrze rośnie na glebach przeciętnych ogrodowych. Lubi gleby wilgotne, szczególnie w okresie kwitnienia. Roślina całkowicie mrozoodporna, nie wymaga okrywania. Preferuje stanowisko słoneczne lub półcieniste. Nowość godna polecenia.',
      //   source: 'http://www.e-katalogroslin.pl/',
      //   height: '2m',
      //   colors: ['biały', 'czerwony'],
      //   chosenColor: '',
      //   floweringDate: 'VII, VIII, IX, X',
      //   conditions: '',
      //   cutting: '',
      //   fertilizing: '',
      //   photo: ['/images/20200826_122049.jpg', '/images/20200826_122058.jpg'],
      //   price: 40,
      // },
      // {
      //   id: '2',
      //   polishName: 'Ketmia syryjska',
      //   latinName: 'Hibiskus syriacus',
      //   type: '',
      //   content: 'Sztywno wyprostowany, wolnorosnący krzew osiągający do 1,5-2 m wys. Liście sezonowe, późno pojawiające się na wiosnę, na jesieni żółte. Kwiaty bardzo efektowne, do 10 cm śr., pojedyncze, podobne do kwiatów malwy, VI-VIII. Odmiany różnią się od siebie zabarwieniem kwiatów: Wymaga próchnicznej, przepuszczalnej ziemi. Może całkowicie zmarznąć w surowe zimy, dlatego wymaga stanowisk osłoniętych i ciepłych oraz dodatkowo okrycia na zimę.',
      //   source: 'http://www.e-katalogroslin.pl/',
      //   height: '1,5-2m',
      //   colors: ['biały', 'fioletowy'],
      //   chosenColor: '',
      //   floweringDate: 'VII, VIII, IX',
      //   conditions: 'słońce, półcień',
      //   cutting: '',
      //   fertilizing: '',
      //   photo: ['/images/20200826_121659.jpg', '/images/20200826_121711.jpg', '/images/20200826_121716.jpg'],
      //   price: 40,
      // },
      // {
      //   id: '3',
      //   polishName: 'Róża',
      //   latinName: 'Rosa',
      //   type: 'The Fairy',
      //   content: 'Kwiaty jasnoróżowe, później bielejące, pełne, małe, 2-3 cm, zebrane w kiście. Liście drobne, błyszczące. Pędy cienkie, przewieszające się i przykrywające podłoże. Wzrost średni, wys. 60-70 cm. Podstawowa róża okrywowa. Odmiana zdrowa, całkowicie odporna na mróz, kwitnąca długo i obficie. ',
      //   source: 'http://www.e-katalogroslin.pl/',
      //   height: '0,5-1m',
      //   colors: ['biały', 'różowy'],
      //   chosenColor: '',
      //   floweringDate: 'VI, VII, VIII, IX, X',
      //   conditions: 'słońce',
      //   cutting: '',
      //   fertilizing: '',
      //   photo: ['/images/20200826_122350.jpg'],
      //   price: 20,
      // },
      // {
      //   id: '4',
      //   polishName: 'Pięciornik krzewiasty',
      //   latinName: 'Potentilla fruticosa',
      //   type: '',
      //   content: 'Niewielki, zaokrąglony krzew, gęsto krzewiący się. Dorasta do 1 m wys. Liście ciemnozielone, pierzasto złożone, składające się z 7 obustronnie owłosionych, bezogonkowych listków. Kwiaty wyrastające na końcach pędów, stosunkowo duże, do 5 cm śr., o promienistej koronie składającej się z 5 płatków zachodzących na siebie. Kwitnie bardzo długo, VI-X. Wymaga słonecznego stanowiska. Najlepiej rośnie na glebach lekkich - piaszczystych lub piaszczysto-gliniastych. Bardzo odporna na ekstremalne warunki odmiana, długo kwitnąca, niepodatna na mączniaka, o wszechstronnym zastosowaniu. Niewymagający, łatwy w uprawie, okrywowy krzew do ogrodów skalnych, na rabaty, do parków, zieleni osiedlowej. Dobrze znosi cięcie. Nadaje się na niskie żywopłoty.',
      //   source: 'http://www.e-katalogroslin.pl/',
      //   height: '0,5-1m',
      //   colors: ['biały', 'różowy', 'żółty'],
      //   chosenColor: '',
      //   floweringDate: 'VI, VII, VIII, IX, X',
      //   conditions: 'słońce',
      //   cutting: '',
      //   fertilizing: '',
      //   photo: ['/images/20200826_122413.jpg'],
      //   price: 20,
      // },



    ],
    loading: {
      active: false,
      error: false,
    },
  },
  cart: {
    products: [],
  },
};
